UserFps - Main Project/UserFps/Models/UsersModel.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace UserFps.Models
{
    public class UsersModel
    {
        [Key]
        [Display(Name = "ID")]
        public int ID { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "User Name")]
        public string UserName { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "First Name")]
        public string FirstName { get; set; }

        [Required]
        [DataType(DataType.Text)]
        [Display(Name = "Last Name")]
        public string LastName { get; set; }

        [Required]
        [DataType(DataType.EmailAddress)]
        [Display(Name = "Email")]
        public string Email { get; set; }
        
        [Required]
        [DataType(DataType.Password)]
        [Display(Name = "Password")]
        public string Password { get; set; }
        
        [DataType(DataType.Text)]
        [Display(Name = "Device ID")]
        public string DeviceId { get; set; }

        public DateTime CreatedDate { get; set; }

        public string TransactionSource { get; set; }
    }
}

UserFps - Main Project/UserFps/Controllers/UsersModelController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Http;
using UserFps.Models;
using System.Data.SqlClient;
using System.Data;
using System.Text;
using UserFps.Classes;
using Newtonsoft.Json.Linq;
using Microsoft.Extensions.Options;

namespace UserFps.Controllers
{
    public class UsersModelController : Controller
    {
        // Dependency injection.
        private readonly UserContext _context; // DB context for project
        private readonly IOptions<ConnectionStrings> _connectionStrings; //connection string used to call stored procedure

        // Associating the DI to a global environment to be accessed by all methods
        public UsersModelController(UserContext context,
                                    IOptions<ConnectionStrings> connectionStrings)
        {
            _context = context;
            _connectionStrings = connectionStrings;
        }

        // GET: UsersModel/Register
        public IActionResult Register()
        {

            return View();
        }

        // POST: UsersModel/Register
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Register(UsersModel account)
        {
            if (ModelState.IsValid)
            {
                //Adds user information to db including the DeviceId thats generated from device they register with
                
                _context.Add(account);
                account.CreatedDate = DateTime.Now;
                account.TransactionSource = "IDC";  //At registration, the user creates an ID
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Login)); //user directed to Login after registration
            }
            return View();
        }
        // GET: UsersModel/Login
        public IActionResult Login()
        {
            return View();
        }

        //POST: UsersModel/Login
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Login(UsersModel usersModel)
        {
            // Vendor return from JS area
            // Grabbing encrypted string from client
            var vendor = Request.Form["ioBlackBox"].ToString();

            // Decrypting string
            var keybytes = Encoding.UTF8.GetBytes("7061737323313233");
            var iv = Encoding.UTF8.GetBytes("7061737323313233");
            var encrypted = Convert.FromBase64String(vendor);
            var decriptedVendorObj = Encrypter.DecryptStringFromBytes(encrypted, keybytes, iv);

            // Creating JSON object in a C# format from returned string
            JObject vendorObj = JObject.Parse(decriptedVendorObj);

            //Instantiate strings and ints to be used for database submissions
            string ven1, ven2, ven3, ven4, ven5;
            string appCode, appName, appVer, lang, plat, oscpu, vend, prod, sec, usrA, bld;
            bool cook, onln;
            string pluginName1, pluginVersion1, pluginName2, pluginVersion2, pluginName3, pluginVersion3, pluginName4, pluginVersion4, pluginName5, pluginVersion5;
            int availHeight, availWidth, colorDepth, height, pixelDepth, width;
            string javascriptVer; int timezone;

            // In this section, The code is separating the JSON object into separate JToken collections to be iterated though are parsed out
            // to be added into its respective DB columns.
            // The Conditional group is to ensure object instances have something in them. Will throw a ArgumentNullException if JToken object is empty
            // If they are empty, all values are set to either null or 0 
            if (_context.Vendor.Where(v => v.VendorName.Equals("ioaa") && v.ServiceActive == true).Any())
            {
                // Each instantiation of the JToken class uses the SelectToken method to find the specific value pertaining 
                // to the desired element it needs to bring back. The SelectToken method takes in a JSONPath argument as a parameter.
                // much like XPath for XML, this is used to iterate through the entire JSON return.
                // For more help, go to http://goessner.net/articles/JsonPath/index.html and http://jsonpath.com/
                IEnumerable<JToken> ioaa = vendorObj.SelectToken("$.Vendors[?(@.Key == 'ioaa')]");
                
                // Each collection is iterated though using the "ElementAt" method to take the value and attach it to the global variable
                // The global variable is then used for the submission of the data into the DB.
                ven1 = (string)ioaa.ElementAt(1);
            }
            else
                ven1 = null;
            // Iobb call returns a string
            if (_context.Vendor.Where(v => v.VendorName.Equals("iobb") && v.ServiceActive == true).Any())
            {
                IEnumerable<JToken> iobb = vendorObj.SelectToken("$.Vendors[?(@.Key == 'iobb')]");
                ven2 = (string)iobb.ElementAt(1);
            }
            else
                ven2 = null;
            // Iocc call returns a string
            if (_context.Vendor.Where(v => v.VendorName.Equals("iocc") && v.ServiceActive == true).Any())
            {
                IEnumerable<JToken> iocc = vendorObj.SelectToken("$.Vendors[?(@.Key == 'iocc')]");
                ven3 = (string)iocc.ElementAt(1);
            }
            else
                ven3 = null;
            // Iodd call returns a string
            if (_context.Vendor.Where(v => v.VendorName.Equals("iodd") && v.ServiceActive == true).Any())
            {
                IEnumerable<JToken> iodd = vendorObj.SelectToken("$.Vendors[?(@.Key == 'iodd')]");
                ven4 = (string)iodd.ElementAt(1);
            }
            else
                ven4 = null;
            // Ioee call returns a string
            if (_context.Vendor.Where(v => v.VendorName.Equals("ioee") && v.ServiceActive == true).Any())
            {
                IEnumerable<JToken> ioee = vendorObj.SelectToken("$.Vendors[?(@.Key == 'ioee')]");
                ven5 = (string)ioee.ElementAt(1);
            }
            else
                ven5 = null;
            // Ioff call. This returns another JSON object. The code parses though the whole object and adds it to the DB.
            // The DB is separated in to multiple tables pertaining to the section of the JSON object and the values are are added to their
            // respective columns. Column names are based off the key names used in the JSON object
            if (_context.Vendor.Where(v => v.VendorName.Equals("ioff") && v.ServiceActive == true).Any())
            {
                // Grabbing Navigator section of Extended Vendor JSON Object
                IEnumerable<JToken> navigator = vendorObj.SelectToken("$.Vendors[?(@.Key == 'ioff')].Data.navigator");
                appCode = (string)navigator.ElementAt(0);
                appName = (string)navigator.ElementAt(1);
                appVer = (string)navigator.ElementAt(2);
                lang = (string)navigator.ElementAt(3);
                plat = (string)navigator.ElementAt(4);
                oscpu = (string)navigator.ElementAt(5);
                vend = (string)navigator.ElementAt(6);
                prod = (string)navigator.ElementAt(7);
                sec = (string)navigator.ElementAt(8);
                usrA = (string)navigator.ElementAt(9);
                cook = (bool)navigator.ElementAt(10);
                onln = (bool)navigator.ElementAt(11);
                bld = (string)navigator.ElementAt(12);

                // Grabbing Plugin section of Extended Vendor JSON Object. Plugins are a nested array of nested objects.
                // For simplification, once the user has logged in, all "Names" from objects are added in one column
                // and all "Versions" are added into the other column. 
                IEnumerable<JToken> firstPlugin = vendorObj.SelectToken("$.Vendors[?(@.Key == 'ioff')].Data.plugins[0]");
                pluginName1 = (string)firstPlugin.ElementAt(0);
                pluginVersion1 = (string)firstPlugin.ElementAt(1);
                IEnumerable<JToken> secondPlugin = vendorObj.SelectToken("$.Vendors[?(@.Key == 'ioff')].Data.plugins[1]");
                pluginName2 = (string)secondPlugin.ElementAt(0);
                pluginVersion2 = (string)secondPlugin.ElementAt(1);
                IEnumerable<JToken> thirdPlugin = vendorObj.SelectToken("$.Vendors[?(@.Key == 'ioff')].Data.plugins[2]");
                pluginName3 = (string)thirdPlugin.ElementAt(0);
                pluginVersion3 = (string)thirdPlugin.ElementAt(1);
                IEnumerable<JToken> fourthPlugin = vendorObj.SelectToken("$.Vendors[?(@.Key == 'ioff')].Data.plugins[3]");
                pluginName4 = (string)fourthPlugin.ElementAt(0);
                pluginVersion4 = (string)fourthPlugin.ElementAt(1);
                IEnumerable<JToken> fifthPlugin = vendorObj.SelectToken("$.Vendors[?(@.Key == 'ioff')].Data.plugins[4]");
                pluginName5 = (string)fifthPlugin.ElementAt(0);
                pluginVersion5 = (string)fifthPlugin.ElementAt(1);

                // Grabbing Screen section of Extended Vendor JSON Object
                IEnumerable<JToken> screen = vendorObj.SelectToken("$.Vendors[?(@.Key == 'ioff')].Data.screen");
                availHeight = (int)screen.ElementAt(0);
                availWidth = (int)screen.ElementAt(1);
                colorDepth = (int)screen.ElementAt(2);
                height = (int)screen.ElementAt(3);
                pixelDepth = (int)screen.ElementAt(4);
                width = (int)screen.ElementAt(5);

                // Grabbing Extra section of Extended Vendor JSON Object
                IEnumerable<JToken> extra = vendorObj.SelectToken("$.Vendors[?(@.Key == 'ioff')].Data.extra");
                javascriptVer = (string)extra.ElementAt(0);

UserFps - Main Project/UserFps/Views/UsersModel/IndexAsync.cshtml
@model IEnumerable<UserFps.Models.UsersModel>
@{
    ViewData["Title"] = "IndexAsync";
}

<h2>IndexAsync</h2>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FirstName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.LastName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Email)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UserName)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Password)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DeviceId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.FirstName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.LastName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Email)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.UserName)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Password)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.DeviceId)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
                    <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>

UserFps - Main Project/UserFps/Views/UsersModel/LoggedIn.cshtml
@{
    ViewData["Title"] = "LoggedIn";
}

<div class="jumbotron">
    <div class="text-center">
        <div style="display:inline-block">
            <h1 class="display-4">Hello @ViewBag.UserName, Welcome to </h1>
        </div>
        <div style="display:inline-block">
            <img style="height:200px;width:200px;display:inline;" alt="Ups-Logo" class=" img-responsive ups_logo" src="~/images/UPS_Logo.png" />
        </div>
    </div>
</div>

UserFps - Main Project/UserFps/Views/UsersModel/Login.cshtml
@model UserFps.Models.UsersModel
@{
    ViewData["Title"] = "Login";
}
<script src="~/js/client.min.js"></script>
<div class="container-fluid ups-signin" style="padding-left: 30%; padding-right: 30%;">
    <div class="row">
        <div class="center-block col-lg-8 body-content" style="float:none;">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <strong>Sign in to <span class="hidden-400">continue</span> <span class="show-400"></span> </strong>
                </div>
                <div class="panel-body">
                    <section>
                        <form asp-action="Login">
                            <fieldset>
                                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                                <div class="row">
                                    <div class="col-lg-12">

                                        @* Language *@
                                        <div class="form-group has-feedback has-success">
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="fa fa-language"></i>
                                                </span>
                                                <select class="form-control" data-toggle="tooltip" id="select" style="cursor: default;" title="Select your language preference." disabled>
                                                    <option>English</option>
                                                </select>
                                                <span class="glyphicon form-control-feedback glyphicon-ok" id="splang" style="padding-right:10px;"></span>
                                            </div>
                                        </div>

                                        @* Username input *@
                                        <div class="form-group has-feedback" id="fgname">
                                            <label for="loginname">User ID</label>
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="fa fa-user"></i>
                                                </span>
                                                <input asp-for="UserName" autofocus="" class="form-control" data-toggle="tooltip" placeholder="ABC1XYZ" title="Enter your User ID (Workstation&nbsp;ID)" />
                                                <span asp-validation-for="UserName" class="text-danger"></span>
                                                <span class="glyphicon form-control-feedback" id="spname"></span>
                                            </div>
                                            <div class="help-block collapse" id="msgname" role="alert">&nbsp;</div>
                                        </div>

                                        @* Password input *@
                                        <div class="form-group has-feedback" id="fgpass">
                                            <label for="password">Password</label>
                                            <div class="input-group">
                                                <span class="input-group-addon">
                                                    <i class="fa fa-key"></i>
                                                </span>
                                                <input asp-for="Password" class="form-control" data-toggle="tooltip" placeholder="Password" title="Enter your Password" />
                                                <span asp-validation-for="Password" class="text-danger"></span>
                                                <span class="glyphicon form-control-feedback" id="sppass"></span>
                                            </div>
                                            <div class="help-block collapse" id="msgpass" role="alert">&nbsp;</div>
                                        </div>

                                        @*DeviceId is generated by the client-js file*@
                                        <div class="form-group">
                                            <input type="hidden" asp-for="DeviceId" class="form-control" id="FingerPrint" />
                                        </div>

                                        @* sign in button *@
                                        <div class="form-group">
                                            <input class="btn btn-lg btn-primary btn-block" id="sbtn" type="submit" value="Login" />
                                        </div>
                                    </div>
                                </div>
                            </fieldset>
                            @* div that is used to generate inputs and scrips from JavaScript code *@
                            <div id="container"></div>
                            @* Input that holds the encrypted JSON object that the serverside pulls in for processing *@
                            <input type="hidden" class="form-control" name="ioBlackBox" id="ioBlackBox" />
                        </form>
                    </section>
                </div>
                <div class="panel-footer">
                    <div class="row">
                        <div class="col-xs-12">
                            <a asp-area="" asp-controller="UsersModel" asp-action="Register">Register as a new user</a><br />
                            <a href="#" onclick="javascript:window.open('HelpInstructions.jsp');return false;">Sign in Help</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    @* Script for VenderCall which is used to generate user data and send it to back end. See file for more details.
        "asp-encode" is a class that uses TagHelpers to help obfuscate the script code with Base64 encoding.
        Reference for whole project needs to be added to file "_ViewImports.cshtml" using just the namespace*@
    
    <script asp-encode="true">
        // Makes the call to the WebApi service and returns the JSON result
        // the JSON result is stored JavaScript code that is injected into the client
        // The code produces information based on the client device used to acess the webpage
        // That infomration is then processed into another JSON object, encrypted, and sent to the server side for processing

        // Variable Initialization
        var array = [];
        var bbInput = document.getElementById('ioBlackBox');
        var container = document.getElementById("container");
        
        // Used to clear existing inputs generated from the previous session
        while (container.hasChildNodes()) {
            container.removeChild(container.lastChild);
        }

        // Once the ajax request returns, it takes the gathered code and injects
        // it into this script tag which then populates the hidden fields to be
        // grabbed by the back end to be stored on the local db
        $(function () {
            $.ajax({
                type: 'POST',
                url: 'https://localhost:44376/api/object',
                dataType: 'json',
                contentType: 'application/json; charset=utf-8',
                success: function (data) {

                    for (key in data) {

                        // setting a variable to the for in loop return for simplification
                        var tmp = data[key]; 

                        // Creating inputs and scripts dynamically according to the return of the service
                        var script = document.createElement("script");
                        script.id = "vendor" + tmp.id;
                        container.appendChild(script);
                        var input = document.createElement("input");
                        input.type = "hidden";
                        input.name = "ven" + tmp.id;
                        input.id = "ven" + tmp.id;
                        container.appendChild(input);
                        container.appendChild(document.createElement("br"));

                        // JQuery version inject code pulled from service call
                        $("#vendor" + tmp.id).append(tmp.vendorCode);

                        // Funciton to set timer
                        doSetTimeout(tmp);
                    }

                    // Since some vendors need timers set to fetch device data, we have to delay the creation
                    // of the JSON object so that that input fields can populate
                    function doSetTimeout(tmp) {
                        setTimeout(function () {

                            // Creating JSON objects returned from vendor code generation using the values inside the generated inputs.
                            // in order to create a proper JSON object, the returns need to be surrounded with quotation marks.
                            // we also need to be aware that some returns will be already in objects.
                            // The if statements looks to see if the return begins with a braket. If so then there is no need to add quotes around a return.
                            if (!$("#ven" + tmp.id).val().match("^{")) {
                                array.push('{"Key":"' + tmp.vendorName + '","Data":"' + $("#ven" + tmp.id).val() + '"}');
                            }
                            else {
                                array.push('{"Key":"' + tmp.vendorName + '","Data":' + $("#ven" + tmp.id).val() + '}');
                            }
                        }, 1000);
                    }

                    // Waiting for input fields to populate
                    setTimeout(function () {

                        // Key and Initialization vector for encrypting the vendor returns
                        // CryptoJS reference is in "_Layout.cshtml"
                        var key = CryptoJS.enc.Utf8.parse(7061737323313233);
                        var iv = CryptoJS.enc.Utf8.parse(7061737323313233);

                        // Inserting individual vendor JSON objects into input and appending commas to each instance to separate objects
                        array.forEach(function (element) {
                            bbInput.value += element + ",";
                        });

                        // Creating JSON object to hold all vendor objects within the ioBlackBox input
                        // it puts the objects within an array as well as removes the last comma for formatting issues.
                        var encryptBB = '[' + bbInput.value;
                        encryptBB = '{"Vendors":' + encryptBB.slice(',', -1) + ']}';

                        // Encrypting the string withing the ioBlackbox input
                        var encrypted = CryptoJS.AES.encrypt(CryptoJS.enc.Utf8.parse(encryptBB), key,
                            {
                                keySize: 128 / 8,
                                iv: iv,
                                mode: CryptoJS.mode.CBC,
                                padding: CryptoJS.pad.Pkcs7
                            });
                        // Inserting the encryption back into the ioBlackBox input
                        bbInput.value = encrypted;

                        // Removing Generated inputs used to capture individual vendor calls
                        while (container.hasChildNodes()) {
                            container.removeChild(container.lastChild);
                        }
                    }, 1000);
                },
                error: function (error) {
                    console.log(error);
                }
            });
        });

    </script>

    @* Using the client-js file, generates a device fingerprint
        from user's device info. The userFingerprint is added to
        the DeviceId hidden input field in the form *@
    <script asp-encode="true">
        var client = new ClientJS();
        var OS = client.getOS();
        var osVersion = client.getOSVersion();
        var browser = client.getBrowser();
        var engineVersion = client.getEngineVersion();
        var language = client.getLanguage();
        var isJava = client.isJava();
        var isSilverlight = client.isSilverlight();

        var userFingerprint = client.getCustomFingerprint(OS, osVersion, browser, engineVersion, language, isJava, isSilverlight);
        document.getElementById("FingerPrint").value = userFingerprint;
    </script>


}

UserFps - Main Project/UserFps/Views/UsersModel/Register.cshtml
@model UserFps.Models.UsersModel

@{
    ViewData["Title"] = "Register";
}

<div class="row">
    <div class="col-sm-4 col-sm-offset-4">
        <h2>Register</h2>
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="UserName" class="control-label"></label>
                <input asp-for="UserName" class="form-control" />
                <span asp-validation-for="UserName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            @*DeviceId is generated by the client-js file*@
            <div class="form-group">
                <input type="hidden" asp-for="DeviceId" class="form-control" id="FingerPrint" />
            </div>
            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

@section Scripts {

    @* Using the client-js file, generates a device fingerprint 
        from user's device info. The userFingerprint is added to 
        the DeviceId hidden input field in the form *@
    <script asp-encode="true">
        var client = new ClientJS();
        var OS = client.getOS();
        var osVersion = client.getOSVersion();
        var browser = client.getBrowser();
        var engineVersion = client.getEngineVersion();
        var language = client.getLanguage();
        var isJava = client.isJava();
        var isSilverlight = client.isSilverlight();

        var userFingerprint = client.getCustomFingerprint(OS, osVersion, browser, engineVersion, language, isJava, isSilverlight);
        document.getElementById("FingerPrint").value = userFingerprint;
    </script>
}